CREATE TABLE IF NOT EXISTS application (
	app_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	description VARCHAR(255) NOT NULL,
	
	version INT UNSIGNED NOT NULL DEFAULT 0,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);