CREATE TABLE IF NOT EXISTS experiment (
	exp_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	app_id INT UNSIGNED NOT NULL,
	name VARCHAR(32) NOT NULL,
	description VARCHAR(255) NOT NULL,
	seed INT UNSIGNED NOT NULL,
	filter JSON,
	status TINYINT UNSIGNED NOT NULL DEFAULT 0,  -- 0:STOPED, 1:ACTIVE

	version INT UNSIGNED NOT NULL DEFAULT 0,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	INDEX (status),
	INDEX (app_id, status)
);

CREATE TABLE IF NOT EXISTS exp_layer (
	lyr_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	exp_id INT UNSIGNED NOT NULL,
	name VARCHAR(32) NOT NULL,
	
	version INT UNSIGNED NOT NULL DEFAULT 0,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	INDEX (exp_id)
);

CREATE TABLE IF NOT EXISTS exp_segment (
	seg_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	lyr_id INT UNSIGNED NOT NULL,
	range_begin INT UNSIGNED NOT NULL,
	range_end INT UNSIGNED NOT NULL,
	seed INT UNSIGNED NOT NULL,
	
	version INT UNSIGNED NOT NULL DEFAULT 0,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	INDEX (lyr_id)
);

CREATE TABLE IF NOT EXISTS exp_group (
	grp_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	seg_id INT UNSIGNED NOT NULL,
	name VARCHAR(32) NOT NULL,
	share INT UNSIGNED NOT NULL,
	bitmap BINARY(125) NOT NULL,
	is_default TINYINT(1) NOT NULL,
	force_hit TEXT NOT NULL DEFAULT '',
	cfg_id INT UNSIGNED NOT NULL DEFAULT 0,		-- 0=null
	
	version INT UNSIGNED NOT NULL DEFAULT 0,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	INDEX (seg_id, is_default)
);

CREATE TABLE IF NOT EXISTS exp_config (
	cfg_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp_id INT UNSIGNED NOT NULL,
	content TEXT NOT NULL,
	
	create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
	stamp BIGINT NOT NULL,
	
	INDEX (grp_id, stamp)
) AUTO_INCREMENT = 1;
